### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by jakeparis** [tyler36/ddev-xhgui#55]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV
- [x] I am using the latest stable version of this add-on

### Expected Behavior

I expected to see a gui on the automatically opened webpage

### Actual Behavior

I got a Slim Framework error:

## Slim Application Error

A website error has occurred. Sorry for the temporary inconvenience.

For what it's worth, the default xhprof interface is working fine.

### Steps To Reproduce

1. `ddev add-on get ddev/ddev-xhgui`
2. `ddev restart`
3. `ddev xhprof on`
4. `ddev xhgui`
5. A webpage automatically opens with the Slim Application error

## config.yaml
These are the customized parts

```
name: bates
type: wordpress
docroot: html
php_version: "8.2"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
performance_mode: none
upload_dirs:
    - wp-content/uploads
use_dns_when_possible: true
timezone: America/New_York
composer_version: "2"
web_environment: []
corepack_enable: true
```

I noticed that there's a `xhgui/nginx.conf` file, so guessed that maybe this only works with nginx. I changed my webserver type to nginx and restarted, but that didn't make any difference.
